name = "random-fact-generator"
type = "javascript"

[build]
  command = "npm install"

[env.production]
  name = "random-fact-generator"

[account]
  id = "508276e4bd39213f3f7baf675a29a105"

[workers_dev]
  route = "/fact"
  zone_id = "052b7f8515fe52b208936484abc847be"
